[package]
name = "raytracer"
version = "0.1.0"
authors = ["Richard Dennehy <richard.dennehy@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"

[dependencies]